server:
  port: 7777

spring:
  jpa:
    show-sql: true
    generate-ddl: true
  flyway:
    enabled: true
  datasource:
    username: sa
    password: sa
    url: jdbc:h2:file:./db/volunteers;AUTO_SERVER=true;AUTO_SERVER=true